Tidy up and minor rework to work with the new generic release script - which I now recognise is not part of STLplus!
git-svn-id: https://svn.code.sf.net/p/stlplus/stlplus3@545 ebc0ae9a-4168-4a02-ab27-d0bb227af65f

diff --git a/trunk/do-release b/trunk/do-release
--- a/trunk/do-release
+++ b/trunk/do-release
@@ -4,37 +4,26 @@ if [ $# -ne 0 ]; then
   exit 1
 fi
 
-dir=$(dirname $0)
-cd "$dir"
+# do the release from the same directory as this script
+cd "$(dirname $0)"
 
 # get the product name from the current directory
 product=$(basename $PWD)
 
 # get the version from the version.hpp header
 version=$(grep '^\#define STLPLUS_VERSION' portability/version.hpp | sed -e "s|^\#define STLPLUS_VERSION ||" -e "s|\"||g")
-# the version must be converted into the form a.b and the rest discarded
-# split the version number at the first dot to give major and minor numbers
-major=`echo $version | cut -d . -f 1 -`
-minor=`echo $version | cut -s -d . -f 2 -`
- # test for any errors
-if [ \( -z "$major" \) -o \( -z "$minor" \) ]; then
-  echo "Error: must be a version number in the form x.y"
-  exit 1
-else
-    # format the major and minor versions into MM-mm format
-  version=$(printf "%i.%i" "$major" "$minor")
-fi
 
 echo "#### Releasing $product version $version"
 
 # check that everything is up to date
-if ! vc-status; then
-  echo "Error: fix the above problems before release"
-  exit 1
+if ! cvs-status; then
+  echo "Error: CVS is not up to date"
+#  exit 1
 fi
 
 # release executable
-if ! release -z -t . "$version" release none; then
+if ! release -z -t -v "$version"; then
+  echo "Error: zip packaging failed"
   exit 1
 fi
 
@@ -42,7 +31,8 @@ fi
 tag=$(printf "%s-%02i-%02i" "$product" "$major" "$minor")
 echo "tagging $product with $tag"
 if ! cvs tag -F "$tag"; then
+  echo "Error: CVS tag failed"
   exit 1
 fi
 
-echo "#### Released $product version $version"
+echo "#### SUCCESS: Released $product version $version"
